# Generated by Django 5.0 on 2023-12-27 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=20)),
                ('ename', models.CharField(max_length=30)),
                ('eemail', models.EmailField(max_length=50)),
                ('eaddress', models.CharField(max_length=40)),
                ('ephonenumber', models.CharField(max_length=15)),
                ('egender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('eMarital', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=10)),
                ('enumberofavailable', models.IntegerField()),
                ('evecationday', models.IntegerField()),
                ('eApprocedvecation', models.BooleanField()),
                ('eSalary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('eDateofBirth', models.DateField()),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
