# Generated by Django 5.0 on 2024-01-30 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_vacationrequest'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vacationrequest',
            table='vacation_request',
        ),
    ]
