# Generated by Django 5.0 on 2024-01-30 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_vacationrequest_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VacationRequest',
            new_name='Vacation',
        ),
        migrations.AlterModelTable(
            name='vacation',
            table='vacation',
        ),
    ]
