# Generated by Django 5.0 on 2024-01-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_delete_vacation_employee_from_date_employee_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=100)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(default='submitted', max_length=100)),
            ],
            options={
                'db_table': 'vacation',
            },
        ),
        migrations.RemoveField(
            model_name='employee',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='status',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='to_date',
        ),
    ]
